# .github/workflows/ci.yml
name: Python CI

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define the job to run on different Python versions
jobs:
  test:

    # Define the environment where the job will run
    runs-on: ubuntu-latest

    # Define a matrix to test on multiple versions of Python
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    # Define the steps to run
    steps:
    - name: Check out code
      uses: actions/checkout@v3  # Check out the repository code

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4  # Set up Python versions
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Install dependencies

    - name: Run tests
      run: |
        pytest  # Run your tests
